{% set version = "1.2.1" %}

package:
  name: trustme
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/trustme/trustme-{{ version }}.tar.gz
  sha256: 6528ba2bbc7f2db41f33825c8dd13e3e3eb9d334ba0f909713c8c3139f4ae47f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - cryptography >=3.1
    - idna >=2.0
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - trustme
  commands:
    - pip check
    - coverage run --source=trustme --branch -m pytest --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=98
  requires:
    - pip
    - pytest
    - coverage
    - pyopenssl
    - service_identity
    - python {{ python_min }}

about:
  home: https://github.com/python-trio/trustme
  summary: '#1 quality TLS certs while you wait, for the discerning tester'
  license: Apache-2.0 or MIT
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE2
  doc_url: https://trustme.readthedocs.io
  doc_source_url: https://github.com/python-trio/trustme/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
