{% set name = "trustme" %}
{% set version = "0.9.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e07b23d70ceed64f3bb36ae4b9abc52354c16c98d45ab037bee2b5fbffe586c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - cryptography
    - idna
    - python >=3.5

test:
  source_files:
    - tests
  imports:
    - trustme
  commands:
    - pip check
    - pytest --cov trustme --cov-fail-under 98
  requires:
    - pip
    - pytest
    - pytest-cov
    - pyopenssl
    - service_identity

about:
  home: https://github.com/python-trio/trustme
  summary: '#1 quality TLS certs while you wait, for the discerning tester'
  license: Apache-2.0 or MIT
  license_file:
    - LICENSE.MIT
    - LICENSE.APACHE2
  doc_url: https://trustme.readthedocs.io
  doc_source_url: https://github.com/python-trio/trustme/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
